// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const upsertOSMVenue = `-- name: UpsertOSMVenue :one
INSERT INTO venues (osm_id, sla_serial, name, address, location, timezone, website, phone, attribution)
VALUES ($1, $2,
        $3, $4,
        ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography,
        $7, $8, $9, $10::text[])
ON CONFLICT (osm_id) DO UPDATE SET
    sla_serial  = COALESCE(EXCLUDED.sla_serial, venues.sla_serial),
    name        = EXCLUDED.name,
    address     = EXCLUDED.address,
    location    = EXCLUDED.location,
    timezone    = EXCLUDED.timezone,
    website     = EXCLUDED.website,
    phone       = EXCLUDED.phone,
    attribution = EXCLUDED.attribution,
    updated_at  = now()
RETURNING id, (xmax = 0)::boolean AS inserted
`

type UpsertOSMVenueParams struct {
	OsmID       *string
	SlaSerial   *string
	Name        string
	Address     *string
	Lng         float64
	Lat         float64
	Timezone    string
	Website     *string
	Phone       *string
	Attribution []string
}

type UpsertOSMVenueRow struct {
	ID       uuid.UUID
	Inserted bool
}

// Inserts or refreshes a venue from OpenStreetMap. A license serial is only overwritten
// when this run matched one, and happy hours are never touched.
func (q *Queries) UpsertOSMVenue(ctx context.Context, arg UpsertOSMVenueParams) (UpsertOSMVenueRow, error) {
	row := q.db.QueryRow(ctx, upsertOSMVenue,
		arg.OsmID,
		arg.SlaSerial,
		arg.Name,
		arg.Address,
		arg.Lng,
		arg.Lat,
		arg.Timezone,
		arg.Website,
		arg.Phone,
		arg.Attribution,
	)
	var i UpsertOSMVenueRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const venueKeysByOSMIDs = `-- name: VenueKeysByOSMIDs :many
SELECT id, osm_id FROM venues WHERE osm_id = ANY($1::text[])
`

type VenueKeysByOSMIDsRow struct {
	ID    uuid.UUID
	OsmID *string
}

func (q *Queries) VenueKeysByOSMIDs(ctx context.Context, osmIds []string) ([]VenueKeysByOSMIDsRow, error) {
	rows, err := q.db.Query(ctx, venueKeysByOSMIDs, osmIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VenueKeysByOSMIDsRow
	for rows.Next() {
		var i VenueKeysByOSMIDsRow
		if err := rows.Scan(&i.ID, &i.OsmID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
