// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Extraction struct {
	ID            uuid.UUID
	SubmissionID  uuid.UUID
	Model         string
	PromptVersion string
	IsHappyHour   bool
	Confidence    float32
	Output        json.RawMessage
	CreatedAt     time.Time
}

type HappyHour struct {
	ID           uuid.UUID
	VenueID      uuid.UUID
	DayOfWeek    int16
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	AllDay       bool
	Deals        json.RawMessage
	Notes        *string
	Confidence   float32
	Verified     bool
	SourceKind   string
	SourceUrl    *string
	ObservedAt   time.Time
	ExtractionID *uuid.UUID
	CreatedAt    time.Time
}

type Submission struct {
	ID            uuid.UUID
	VenueID       uuid.UUID
	Kind          string
	SourceUrl     *string
	ObjectKey     *string
	ContentSha256 *string
	SubmittedBy   *uuid.UUID
	Status        string
	CreatedAt     time.Time
}

type Venue struct {
	ID            uuid.UUID
	OsmID         *string
	SlaSerial     *string
	GooglePlaceID *string
	Name          string
	Address       *string
	Location      interface{}
	Timezone      string
	Website       *string
	Phone         *string
	Attribution   []string
	CrawlStatus   string
	OwnerLocked   bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type VisibleHappyHour struct {
	ID           uuid.UUID
	VenueID      uuid.UUID
	DayOfWeek    int16
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	AllDay       bool
	Deals        json.RawMessage
	Notes        *string
	Confidence   float32
	Verified     bool
	SourceKind   string
	SourceUrl    *string
	ObservedAt   time.Time
	ExtractionID *uuid.UUID
	CreatedAt    time.Time
}
