// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVenue = `-- name: GetVenue :one
SELECT v.id, v.name, v.address, v.timezone,
       ST_Y(v.location::geometry)::float8 AS lat,
       ST_X(v.location::geometry)::float8 AS lng,
       v.website, v.phone, v.attribution, v.updated_at,
       EXISTS (
           SELECT 1 FROM visible_happy_hours h
           WHERE h.venue_id = v.id
             AND pleb_hh_active(h.day_of_week, h.start_time, h.end_time, h.all_day,
                                $1::timestamptz AT TIME ZONE v.timezone)
       )::boolean AS active_now
FROM venues v
WHERE v.id = $2
`

type GetVenueParams struct {
	EvaluatedAt time.Time
	ID          uuid.UUID
}

type GetVenueRow struct {
	ID          uuid.UUID
	Name        string
	Address     *string
	Timezone    string
	Lat         float64
	Lng         float64
	Website     *string
	Phone       *string
	Attribution []string
	UpdatedAt   time.Time
	ActiveNow   bool
}

func (q *Queries) GetVenue(ctx context.Context, arg GetVenueParams) (GetVenueRow, error) {
	row := q.db.QueryRow(ctx, getVenue, arg.EvaluatedAt, arg.ID)
	var i GetVenueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.Lat,
		&i.Lng,
		&i.Website,
		&i.Phone,
		&i.Attribution,
		&i.UpdatedAt,
		&i.ActiveNow,
	)
	return i, err
}

const searchVenues = `-- name: SearchVenues :many
WITH origin AS (
    SELECT ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography AS pt
),
candidates AS (
    SELECT v.id, v.name, v.address, v.timezone, v.location,
           ST_Distance(v.location, o.pt)::float8 AS distance_m
    FROM venues v, origin o
    WHERE ST_DWithin(v.location, o.pt, $9::float8)
)
SELECT c.id, c.name, c.address, c.timezone,
       ST_Y(c.location::geometry)::float8 AS lat,
       ST_X(c.location::geometry)::float8 AS lng,
       c.distance_m,
       EXISTS (
           SELECT 1 FROM visible_happy_hours h
           WHERE h.venue_id = c.id
             AND pleb_hh_active(h.day_of_week, h.start_time, h.end_time, h.all_day,
                                $1::timestamptz AT TIME ZONE c.timezone)
       )::boolean AS active_now
FROM candidates c
WHERE EXISTS (
        SELECT 1 FROM visible_happy_hours h
        WHERE h.venue_id = c.id
          AND ($2::smallint IS NULL OR h.day_of_week = $2::smallint)
          AND ($3::timestamptz IS NULL
               OR pleb_hh_active(h.day_of_week, h.start_time, h.end_time, h.all_day,
                                 $3::timestamptz AT TIME ZONE c.timezone))
      )
  AND ($4::float8 IS NULL
       OR (c.distance_m, c.id) > ($4::float8, $5::uuid))
ORDER BY c.distance_m, c.id
LIMIT $6::int
`

type SearchVenuesParams struct {
	EvaluatedAt   time.Time
	Day           *int16
	ActiveAt      *time.Time
	AfterDistance *float64
	AfterID       *uuid.UUID
	RowLimit      int32
	Lng           float64
	Lat           float64
	RadiusM       float64
}

type SearchVenuesRow struct {
	ID        uuid.UUID
	Name      string
	Address   *string
	Timezone  string
	Lat       float64
	Lng       float64
	DistanceM float64
	ActiveNow bool
}

// Venues within radius_m of a point that have at least one visible happy hour
// matching the optional day and active_at filters, keyset-paginated by (distance, id).
func (q *Queries) SearchVenues(ctx context.Context, arg SearchVenuesParams) ([]SearchVenuesRow, error) {
	rows, err := q.db.Query(ctx, searchVenues,
		arg.EvaluatedAt,
		arg.Day,
		arg.ActiveAt,
		arg.AfterDistance,
		arg.AfterID,
		arg.RowLimit,
		arg.Lng,
		arg.Lat,
		arg.RadiusM,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVenuesRow
	for rows.Next() {
		var i SearchVenuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Timezone,
			&i.Lat,
			&i.Lng,
			&i.DistanceM,
			&i.ActiveNow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleHappyHoursForVenues = `-- name: VisibleHappyHoursForVenues :many
SELECT venue_id, day_of_week, start_time, end_time, all_day, deals, notes,
       confidence, verified, source_kind, source_url, observed_at
FROM visible_happy_hours
WHERE venue_id = ANY($1::uuid[])
ORDER BY venue_id, day_of_week, start_time NULLS FIRST
`

type VisibleHappyHoursForVenuesRow struct {
	VenueID    uuid.UUID
	DayOfWeek  int16
	StartTime  pgtype.Time
	EndTime    pgtype.Time
	AllDay     bool
	Deals      json.RawMessage
	Notes      *string
	Confidence float32
	Verified   bool
	SourceKind string
	SourceUrl  *string
	ObservedAt time.Time
}

func (q *Queries) VisibleHappyHoursForVenues(ctx context.Context, venueIds []uuid.UUID) ([]VisibleHappyHoursForVenuesRow, error) {
	rows, err := q.db.Query(ctx, visibleHappyHoursForVenues, venueIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleHappyHoursForVenuesRow
	for rows.Next() {
		var i VisibleHappyHoursForVenuesRow
		if err := rows.Scan(
			&i.VenueID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.Deals,
			&i.Notes,
			&i.Confidence,
			&i.Verified,
			&i.SourceKind,
			&i.SourceUrl,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
